### ISSUE TITLE
Swap latitude and longitude for WithinCircle

### ISSUE THREAD

**Issue by oleksii-volkovskyi** [treedomtrees/commercetools-where-string-builder#1]
Hello,
Thanks for a great tool, it's really helpful!

I found a small issue in your implementation. 
```
WithinCircle: (field: string, latitude: number, longitude: number, radius: number) => string
```

Commmercetools has different parameters order: longitude should be first.

https://docs.commercetools.com/api/predicates/query
```
// Query GeoJSON field within a circle
// The two first parameters are the longitude and latitude of the circle's center.
// The third parameter is the radius of the circle in meter.
geoLocation within circle(13.37770, 52.51627, 1000)
```

**Comment by vivedo** [comment]
Nice catch!
Looks like a quick fix, would you be able to open a pull request?

I believe it is appropriate to update the function signature to match the commercetools order of parameters, so that calling `WithinCircle('foo', 123, 456, 789)` will result in `geoLocation within circle(123, 456, 789)`

Thank you!

**Comment by oleksii-volkovskyi** [comment]
Fixes here:
https://github.com/treedomtrees/commercetools-where-string-builder/pull/2
